DROP TABLE IF EXISTS failed_events;
DROP TABLE IF EXISTS report_links;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS clicks;
DROP TABLE IF EXISTS links;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS clients;

DROP EXTENSION IF EXISTS pgcrypto;
